# Generated by Django 5.1.2 on 2024-11-01 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_rename_completed_task_iscompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
